### ISSUE TITLE
interactions index: unintended code block

### ISSUE THREAD

**Issue by EmreTech** [Pycord-Development/guide#108]
**Describe the bug**

In the index page for the Interactions guide, there is an unintended code block.
<img width="1904" alt="Screen Shot 2022-05-03 at 11 36 59" src="https://user-images.githubusercontent.com/50607143/166520305-24291407-1c2c-4a3d-99e5-0bc3f99168de.png">

**To Reproduce**

1. Go to the page for the Interactions index
2. You'll see a code block when the guide is listing the different types of Context Menu commands

**Expected behavior**

The text is formatted correctly to not be a code block.

**Additional Context**

I haven't tested to see if this issue appears in the master branch, but it definitely does appear in the production branch.

**Checklist**

 - [x] This is an issue with the build, not a spelling or grammar mistake.
 - [x] I have the latest version of the guide.

**Comment by EmreTech** [comment]
Quick look at the master branch commits, it does seem to be fixed. However, I don't think the fix was merged to production yet.

**Comment by BobDotCom** [comment]
Fixed

https://62859beb63300e0008a6c20e--pycord.netlify.app/interactions/
