### ISSUE TITLE
Do not suggest using `sqlite3`

### ISSUE THREAD

**Issue by Astrea49** [Pycord-Development/guide#137]
**Is your feature request related to a problem? Please describe.**
As of right now, [`sqlite3`](https://guide.pycord.dev/getting-started/rules-and-common-practices#sqlite) is recommended on the "Rules and Common Practices" page. However, `sqlite3` is synchronous and blocking, which, when considering many people reading this part of the guide are reading it with the idea that they can use this in their asynchronous bot, is... not great.

**Describe the solution you'd like**
Recommend `aiosqlite` instead. Maybe put a warning *against* using the Standard Library `sqlite3`.

**Describe alternatives you've considered**
`asqlite` exists, but I can understand not wanting to recommend that.
Leaving the page as-is is bound to confuse developers.

**Comment by itsnotrin** [comment]
+1
