### ISSUE TITLE
a feature to disabling the user from clicking any buttons for given time 

### ISSUE THREAD

**Issue by cheemzboi** [Pycord-Development/guide#241]
**Is your feature request related to a problem? Please describe.**
i made a bot in which i want that if user enter wrong answer in the modal (self.children[0].value)
all ui components should be disabled for him 

**Describe the solution you'd like**

I want  a feature that can help me ease this process

**Describe alternatives you've considered**

i tried using timeout asyncio sleep and many stuff but didnt quite get the desired result

**Additional context**

**Comment by Lulalaby** [comment]
This isn't something a lib should care of. Sorry, we won't implement this. That's a bot devs job.
