### ISSUE TITLE
Syntax error in docs/extensions/commands/prefixed-commands.mdx

### ISSUE THREAD

**Issue by Developer-Anony** [Pycord-Development/guide#261]
### Where is the error?

The error is in [Line 302](https://github.com/Pycord-Development/guide/blob/main/docs/extensions/commands/prefixed-commands.mdx?plain=1#L302)

-------------------------------

### What's the error?

Basically, is missing some **quotation marks** that are needed when content is a string.

![Error show](https://user-images.githubusercontent.com/108473820/204581066-014e0f9b-d57d-4510-b06b-0ab159d0630b.png "Missing quotation marks")

As all can see, there are some missing quotation marks at the end of "You guessed it!" response.

Hopefully it'll be fixed soon, will it?

**Comment by EmreTech** [comment]
> Hopefully it'll be fixed soon, will it?

If you want it to be fixed sooner, then why not open a PR?

**Comment by Developer-Anony** [comment]
> If you want it to be fixed sooner, then why not open a PR?

It was just an expression...
*I just wanted to let them know the error*
