### ISSUE TITLE
Fixing guide on Cogs

### ISSUE THREAD

**Issue by TasfiqulTapu** [Pycord-Development/guide#309]
**Is your feature request related to a problem? Please describe.**
The guide on [Cogs](https://guide.pycord.dev/popular-topics/cogs) seems to be not working. First of all, it was never mentioned that `bot.load_extension()` needa to be awaited. Furthermore, function `setup` also needs to be an async function with `bot.add_cog()` requiring to be awaited

**Describe the solution you'd like**
Someone more experienced in Pycord needs to review if these problems are correct. If so, I can submit a PR with the changes necessary 

**Describe alternatives you've considered**
Let everyone suffer 🤗

**Additional context**
![Screenshot_2023-04-22-20-33-48-015-edit_com.replit.app.jpg](https://user-images.githubusercontent.com/66732331/233791025-3e454e94-5e99-4539-8407-1772a0ff6904.jpg)
![Screenshot_2023-04-22-20-34-25-618-edit_com.replit.app.jpg](https://user-images.githubusercontent.com/66732331/233791034-d5b5b68c-89a7-44e5-aff1-7873973c8ac1.jpg)

**Comment by plun1331** [comment]
For the guide to work, you need to be using pycord, not discord.py

**Comment by TasfiqulTapu** [comment]
Sorry my bad. It seems that somehow discord.py and py-cord both got installed. I'll close this. Sorry for the inconvenience.

**Comment by Lulalaby** [comment]
lol
