### ISSUE TITLE
Invalid 404 links for events

### ISSUE THREAD

**Issue by Quantum-Codes** [Pycord-Development/guide#327]
### Summary

Most links on the **event handler** topic are 404 pages.

### Reproduction Steps

Go here https://guide.pycord.dev/getting-started/more-features

Under event handlers, click on few links. Most redirect to 404 pages. Examples:
1. https://docs.pycord.dev/en/stable/api.html#discord.Intents
2. https://docs.pycord.dev/en/stable/api.html#discord.Bot.event
3. https://docs.pycord.dev/en/stable/api.html#discord.on_member_join 

### Expected Results

The links should redirect to correct pages

### Actual Results

Links are 404 pages 

### System Information

Chrome

### Checklist

- [X] I have searched the open issues for duplicates.

**Comment by Lulalaby** [comment]
Triaging as high prio.

@Pycord-Development/contributors please look into this :)
