### ISSUE TITLE
Syntax error in Pycord Guide > Interactions > Application commands > Contextual menus > User Commands

### ISSUE THREAD

**Issue by Over1185** [Pycord-Development/guide#348]
### Summary

A syntax error in the User Commands code

### Reproduction Steps

Hi I am new to the community and I was reviewing the Pycord Guide, but I found a syntax error in the Context Menus section, specifically in the User Commands section, the error is that if you put the **guild.ids=[]** attribute in the decorator, the User Command does not work, but if you remove it magically works. On the assumption that I have it wrong, I would like you to add an explanation of how to do it right in the Pycord Guide.

Explanatory video

https://github.com/Pycord-Development/guide/assets/92834159/f0c2cc11-29d6-448c-a79c-d418c41e92a6

### Expected Results

If this error does not occur, it should run normally.

### Actual Results

Gives https error or simply does not give error, but it does not work.

### Checklist

- [x] I have searched the open issues for duplicates.

### Additional Context

I am Hispanic and my English is very bad, so I used Deepl's translator to express myself, so I apologize if there is something wrong written.

**Comment by ChickenDevs** [comment]
You are supposed to replace `...` with the Guild ID of the server you are testing in. (Such as `881207955029110855`) Will update the guide to make this clearer.

**Comment by Over1185** [comment]
Perfect, thank you very much for making the guide a little clearer.
