### ISSUE TITLE
Create Your First Bot Tab

### ISSUE THREAD

**Issue by M7ilan** [Pycord-Development/guide#368]
### Summary

Old Tutorial

### Reproduction Steps

I followed the instructions in [**Creating Your First Bot**](https://guide.pycord.dev/getting-started/creating-your-first-bot), and what led me here is the [**Coding the Basics**](https://guide.pycord.dev/getting-started/creating-your-first-bot#coding-the-basics) section. The tab itself looks outdated, along with the images and instructions. _I would love to contribute to fixing this, maybe_.

Regarding the [**Coding the Basics**](https://guide.pycord.dev/getting-started/creating-your-first-bot#coding-the-basics) section, I encountered an error, which is as follows:

```bash
Traceback (most recent call last):
  File "PATH\Pycord\First Project\bot.py", line 6, in <module>
    bot = discord.Bot()
AttributeError: module 'discord' has no attribute 'Bot'
```

### Expected Results

I expected to have a working code and clear instructions because one example that confused me is [**Inviting the bot**](https://guide.pycord.dev/getting-started/creating-your-first-bot#inviting-the-bot). It says, "Go to the OAuth2 tab in the left pane and select `bot` and `applications.commands` as scopes." However, in the Discord Dev Portal, there are two buttons inside OAuth2, namely `General` and `URL Generator`, but it doesn't mention these.

This isn't a major issue; what I want to convey is that the information in the tab appears outdated, and I haven't progressed to the other tabs beyond this point.

Regarding the code, as I mentioned earlier, I encountered an error, and I expected the code to work without any issues.

### Actual Results

Encountered an error and got lost in the middle of the instructions.

### System Information

Windows 10
Python 3.11.1
Google Chrome
VSCode for running the code.

### Checklist

- [X] I have searched the open issues for duplicates.

**Comment by Lulalaby** [comment]
We're aware of the outdated information.
There were contributions to fix the Screenshots and stuff but we want to use our own branding so we decline any contribution for that. 

We've just haven't had time to fix it yet.
But feel free to update the text and code examples.
