### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by TheDino32519** [Pycord-Development/guide#39]
**Translation**
I suggest translations for: German, French, Italian and Vietnamese.

**Comment by BruceCodesGithub** [comment]
Thanks for the suggestions!
Translations will be taken care of later.

**Comment by VincentRPS** [comment]
Shouldn’t be closed as it’s not actually finished yet

**Comment by BruceCodesGithub** [comment]
> Shouldn’t be closed as it’s not actually finished yet

This will be taken care of later, and we should start a new, more descriptive issue for that once it's time for translations.

**Comment by itsnotrin** [comment]
Agree with Bruce

**Comment by RGBCube** [comment]
i can translate for Turkish too

**Comment by Kertrix** [comment]
I would gladly translate into french.
