### ISSUE TITLE
Meta: Git commits directly to main

### ISSUE THREAD

**Issue by EmreTech** [Pycord-Development/guide#47]
Currently, for collaborators (people that can directly commit to this repo), you cannot directly commit to the main branch. I do understand why this is the case, but it's not the solution for all commits. The only type of commits that should have this restriction is commits that add WIP things and aren't immediate.

For example, if you're going to push a commit to main that fixes only one spelling error or multiple ones in the same file, then it should be committed directly to main. However, if you're going around fixing spelling errors in multiple files, then it should be indirectly committed to main (new branch, PR, merge).

Remember, **this applies only to people that can commit directly to this repo.** If you do not have such permissions, then ignore this issue.

**Comment by EmreTech** [comment]
I'm sorry, why close this?

**Comment by Dorukyum** [comment]
Branch protection seems to be removed.
