### ISSUE TITLE
Make the examples more professional

### ISSUE THREAD

**Issue by BobDotCom** [Pycord-Development/guide#52]
**Is your feature request related to a problem? Please describe.**
The examples (particularly the discord chat) have somewhat childish and "edgy" jokes. While these jokes have their time and place, it would be better to uphold a more professional facade in our guide. New users judge will whether they'd like to use our package based off of what's in the guide, so while light and playful content is ok, we should pick topics that appeal to everyone.

![Screen Shot 2022-03-20 at 1 20 21 PM](https://user-images.githubusercontent.com/71356958/159176760-363100a8-b1e1-4061-bc3e-df7097070124.png)
![Screen Shot 2022-03-20 at 1 24 28 PM](https://user-images.githubusercontent.com/71356958/159176917-17616f89-7adc-40e6-8fe7-06bc6c791518.png)

**Describe the solution you'd like**
Examples should be changed to fit a more professional appearance.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by EmreTech** [comment]
I do agree. I was going to swap the profiles with generic profiles, but then I think Bruce said I couldn't.

**Comment by BruceCodesGithub** [comment]
> I do agree. I was going to swap the profiles with generic profiles, but then I think Bruce said I couldn't.

You can swipe the profile pictures with downloaded images.

**Comment by BruceCodesGithub** [comment]
Fixed with commit d24c8d568069dca265e4af6c0116a7e73e475f6a
