### ISSUE TITLE
Meta: issue/PR labels

### ISSUE THREAD

**Issue by EmreTech** [Pycord-Development/guide#60]
**Is your feature request related to a problem? Please describe.**
Like the main repository, this repository needs labels for issues/PRs.

**Describe the solution you'd like**
Add the following labels:
- feature
- bug
- status
- priority
And possibly more depending on what's needed.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Dorukyum** [comment]
All listed labels have been created.
