### ISSUE TITLE
Syntax Error (Modal)

### ISSUE THREAD

**Issue by DTheIcyDragon** [Pycord-Development/guide#61]
**Syntax Mistake**

In the Modal tutorial is a bracket missing

**Screenshots**
![Unbenannt](https://user-images.githubusercontent.com/74721808/159561794-4b57be5a-95a8-4a6e-a004-3789ec4e2685.png)

**Checklist**

 - [ ] This is an issue with the build, not a spelling or grammar mistake.
 - [x] I have the latest version of the guide.

ᵐʸ ᶠⁱʳˢᵗ ⁱˢˢᵘᵉ ❤️

**Comment by EmreTech** [comment]
Good job finding this! You could also make this your first contribution to the Guide

**Comment by krittick** [comment]
Note that the Modal guide is also currently a WIP and will be getting major updates in the next day or two.
