### ISSUE TITLE
Cogs reference for application commands

### ISSUE THREAD

**Issue by Dorukyum** [Pycord-Development/guide#75]
**Describe the solution you'd like**
A guide page made for application command cogs would be nice.

**Additional context**
There's only a cogs page for ext.commands at the moment (and an example cog in the ext.bridge guide).

**Comment by EmreTech** [comment]
Technically, there is a section in the slash commands guide about cogs. But that section should be copied over to context menus or moved to a separate guide altogether.

**Comment by Dorukyum** [comment]
or we could move the current Cogs guide (for ext.commands) to the App Commands directory and add a new guide to ext.commands that references this one.
